// content/missions.ts — Problem statements data (§5.4)
import { Mission } from "./types";

export const missions: Mission[] = [
  {
    id: "YG-01",
    company: { name: "[Company A]", logo: "" },
    title: "[AI-Powered Campus Safety System]",
    domain: "AI/ML",
    difficulty: 3,
    background:
      "[Describe the real-world context of the problem. Why does it matter? What's the current state?]",
    challenge:
      "[Clearly state the problem. What specifically needs to be built or solved?]",
    deliverables: [
      "[Working prototype / MVP]",
      "[Technical documentation]",
      "[5-minute demo video]",
      "[Source code on GitHub]",
    ],
    resources: ["[Dataset link]", "[API documentation]", "[Development tools]"],
    mentors: ["[Mentor Name, Designation, Company]"],
    linkedWorkshopId: "WS-01",
  },
  {
    id: "YG-02",
    company: { name: "[Company B]", logo: "" },
    title: "[Smart Supply Chain Dashboard]",
    domain: "Web & Mobile",
    difficulty: 4,
    background:
      "[Describe the real-world context of the problem. Why does it matter?]",
    challenge: "[Clearly state what needs to be built or solved.]",
    deliverables: [
      "[Working prototype / MVP]",
      "[Technical documentation]",
      "[5-minute demo video]",
      "[Source code on GitHub]",
    ],
    resources: ["[Dataset or API link]"],
    mentors: ["[Mentor Name, Designation, Company]"],
    linkedWorkshopId: "WS-02",
  },
  {
    id: "YG-03",
    company: { name: "[Company C]", logo: "" },
    title: "[IoT-Based Energy Monitor for Campus Buildings]",
    domain: "IoT & Embedded",
    difficulty: 4,
    background: "[Real-world context of the problem.]",
    challenge: "[What specifically needs to be solved?]",
    deliverables: [
      "[Working prototype / MVP]",
      "[Technical documentation]",
      "[Demo video]",
      "[Source code]",
    ],
    resources: ["[Hardware kit specs]", "[API documentation]"],
    mentors: ["[Mentor Name, Designation, Company]"],
    linkedWorkshopId: "WS-03",
  },
  {
    id: "YG-04",
    company: { name: "[Company D]", logo: "" },
    title: "[FinTech Fraud Detection Pipeline]",
    domain: "FinTech",
    difficulty: 5,
    background: "[Real-world context.]",
    challenge: "[The specific challenge.]",
    deliverables: [
      "[Working prototype]",
      "[Documentation]",
      "[Demo]",
      "[Source code]",
    ],
    resources: ["[Synthetic transaction dataset]"],
    mentors: ["[Mentor Name]"],
  },
  {
    id: "YG-05",
    company: { name: "[Company E]", logo: "" },
    title: "[HealthTech Patient Triage Assistant]",
    domain: "HealthTech",
    difficulty: 3,
    background: "[Context of the healthcare problem.]",
    challenge: "[What needs to be built.]",
    deliverables: ["[Prototype]", "[Docs]", "[Demo]", "[Code]"],
    mentors: ["[Mentor Name]"],
  },
  {
    id: "YG-LOCKED",
    company: { name: "Coming Soon", logo: "" },
    title: "More missions unlock soon",
    domain: "AI/ML",
    difficulty: null,
    background: "",
    challenge: "",
    deliverables: [],
    mentors: [],
    locked: true,
  },
];

export const domains = [
  "AI/ML",
  "Web & Mobile",
  "Cybersecurity",
  "IoT & Embedded",
  "Data Analytics",
  "FinTech",
  "HealthTech",
  "EdTech",
  "AgriTech",
  "Sustainability",
  "Open Innovation",
] as const;
