// content/speakers.ts — Guest speaker data (§7)
import { Speaker } from "./types";

export const speakers: Speaker[] = [
  {
    id: "SP-01",
    name: "[Speaker Name]",
    designation: "[CTO / Head of AI]",
    company: { name: "[Company A]", logo: "" },
    bio: "[2–3 line bio describing expertise, achievements, and what they bring to Yugmora.]",
    photo: "",
    linkedin: "[LinkedIn URL]",
    session: "[Workshop on AI/ML for Real-World Applications]",
    roles: ["Keynote", "Workshop"],
  },
  {
    id: "SP-02",
    name: "[Speaker Name]",
    designation: "[VP Engineering]",
    company: { name: "[Company B]", logo: "" },
    bio: "[Bio describing expertise and background.]",
    photo: "",
    linkedin: "[LinkedIn URL]",
    session: "[Full-Stack Development: From Idea to MVP]",
    roles: ["Workshop", "Mentor"],
  },
  {
    id: "SP-03",
    name: "[Speaker Name]",
    designation: "[IoT Lead]",
    company: { name: "[Company C]", logo: "" },
    bio: "[Bio describing expertise.]",
    photo: "",
    linkedin: "[LinkedIn URL]",
    session: "[IoT Prototyping with Arduino and Raspberry Pi]",
    roles: ["Workshop"],
  },
  {
    id: "SP-04",
    name: "[Speaker Name]",
    designation: "[Data Science Manager]",
    company: { name: "[Company D]", logo: "" },
    bio: "[Bio.]",
    photo: "",
    linkedin: "[LinkedIn URL]",
    session: "[Data Analytics and Visualization]",
    roles: ["Workshop", "Judge"],
  },
  {
    id: "SP-05",
    name: "[Speaker Name]",
    designation: "[Security Architect]",
    company: { name: "[Company E]", logo: "" },
    bio: "[Bio.]",
    photo: "",
    linkedin: "[LinkedIn URL]",
    session: "[Cybersecurity Fundamentals for Developers]",
    roles: ["Workshop", "Mentor"],
  },
];
